{% set name = "irreptables" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/irreptables-{{ version }}.tar.gz
  sha256: 33fd913a102befacd339cbbc5259acae782edc47ca35fe49492f001393eb3b82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy >=1.0
    - spglib >=1.14
    - lazy-property
    - click

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stepan-tsirkin/irrep
  summary: Tables of characters of irreducible representations for double space groups. Part of 'irrep' package
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
